src/accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("login", views.login_page, name="page-login"),
    path("settings", views.settings_page, name="page-settings"),
    path("api/login", views.login_action, name="api-login"),
    path("api/logout", views.logout_action, name="api-logout"),
    path("api/user", views.user_api, name="api-user"),
    path("api/user/<str:username>", views.user_api, name="api-user-one"),
]

src/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect


def home(request: HttpRequest) -> HttpResponse:
    return HttpResponseRedirect(reverse("posts:page-posts"))


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("accounts.urls", "accounts"), namespace="accounts")),
    path("", include(("posts.urls", "posts"), namespace="posts")),
    path("", include(("lights.urls", "lights"), namespace="lights")),
    path("", include(("finance.urls", "finance"), namespace="finance")),
    path("", home, name="home"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/accounts/views.py
from typing import Optional
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.db.utils import IntegrityError
from django.urls import reverse, resolve
from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponseRedirect,
    HttpResponseBadRequest,
    HttpResponseNotFound,
    HttpResponseNotAllowed,
    HttpResponseServerError,
)


def login_page(request: HttpRequest) -> HttpResponse:
    if request.method != "GET":
        return HttpResponseNotAllowed(["GET"])
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("home"))
    return render(request, "accounts/login_page.html")


def settings_page(request: HttpRequest) -> HttpResponse:
    if request.method != "GET":
        return HttpResponseNotAllowed(["GET"])
    return render(request, "accounts/settings_page.html", {"title": "Settings"})


def login_action(request: HttpRequest) -> HttpResponse:
    if request.method != "POST":
        return HttpResponseNotAllowed(["POST"])

    body = request.POST
    username = body.get("username")
    password = body.get("password")
    next_page = body.get("next")

    if username is None or password is None:
        return HttpResponseBadRequest("Invalid username or password")

    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseBadRequest("Invalid username or password")
    login(request=request, user=user)

    next_url: Optional[str] = None
    if next_page:
        try:
            next_url = next_page if resolve(next_page) else None
        except:
            pass
    response = HttpResponse()
    response["HX-Redirect"] = next_url or reverse("home")
    return response


@login_required
def logout_action(request: HttpRequest) -> HttpResponse:
    if request.method != "GET":
        return HttpResponseNotAllowed(["GET"])

    logout(request=request)
    response = HttpResponse()
    response["HX-Redirect"] = reverse("accounts:page-login")
    return response


@login_required
def user_api(request: HttpRequest, username: Optional[str] = None) -> HttpResponse:
    if request.method == "POST":
        return create_user(request)
    if request.method == "DELETE":
        return delete_user(request, username)
    return HttpResponseNotAllowed(["POST", "DELETE"])


def create_user(request: HttpRequest) -> HttpResponse:
    body = request.POST
    username = body.get("username")
    password = body.get("password")

    if username is None or password is None:
        return HttpResponseBadRequest("Username and password required")

    try:
        if "isAdmin" in body and body.get("isAdmin"):
            User.objects.create_superuser(
                username=username,
                password=password,
                email=None,
            )
        else:
            User.objects.create_user(
                username=username,
                password=password,
            )
    except IntegrityError:
        return HttpResponseBadRequest(f'User with name "{username}" already exists')
    except:
        return HttpResponseServerError("An unknown error occurred")
    return HttpResponse()


def delete_user(request: HttpRequest, username: Optional[str]) -> HttpResponse:
    if username is None:
        return HttpResponseBadRequest("Username must be provided to delete")

    try:
        user = User.objects.get(username=username)
    except:
        return HttpResponseNotFound(f'User with username "{username}" not found')
    user.delete()
    return HttpResponse()

src/accounts/templates/accounts/login_page.html
{% extends 'base_page.html' %}

{% load static %}

{% block title %}
  Login
{% endblock %}

{% block style %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts/login_page.css' %}">
{% endblock %}

{% block body %}
  <main class="login-outer">
    <div class="login-inner">
      <h1 class="text-title login-title">Welcome!</h1>
      <form
        hx-post="{% url 'accounts:api-login' %}"
        hx-swap="none"
        hx-on::before-request="
          updateById('login-error', { text: '', style: { display: 'none' } });
          updateById('login-button', { text: 'Loading...', enabled: false });
        "
        hx-on::after-request="updateById('login-button', { text: 'Log In', enabled: true });"
        hx-on::response-error="
          updateById('login-error', {
            text: event.detail.xhr.responseText,
            style: { display: 'block' },
          });
        "
      >
        {% csrf_token %}
        <div>
          <div class="login-label text-caption">
            <label for="username-input">Username</label>
          </div>
          <div class="login-input-container">
            <input
              id="username-input"
              class="text-body login-input"
              name="username"
              type="text"
              placeholder="Username"
              autocomplete="off"
              autocapitalize="off"
            >
          </div>
        </div>
        <div>
          <div class="login-label text-caption">
            <label for="password-input">Password</label>
          </div>
          <div class="login-input-container">
            <input
              id="password-input"
              class="text-body login-input"
              name="password"
              type="password"
              placeholder="Password"
              autocomplete="off"
              autocapitalize="off"
            >
          </div>
        </div>
        {% if request.GET.next %}
          <input
            type="hidden"
            name="next"
            value="{{ request.GET.next }}"
          >
        {% endif %}
        <div class="login-button-container">
          <button
            id="login-button"
            class="button-primary submit-button login-button"
            type="submit"
          >
            Log In
          </button>
        </div>
        <div
          id="login-error"
          class="text-body login-error"
          style="display: none;"
        ></div>
      </form>
    </div>
  </main>
{% endblock %}

src/accounts/templates/accounts/settings_page.html
{% extends 'nav_page.html' %}

{% load static %}

{% block title %}
  Settings
{% endblock %}

{% block style %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts/settings_page.css' %}">
{% endblock %}

{% block body %}
  <main></main>
{% endblock %}