src/finance/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("stocks", views.stocks_page, name="page-stocks"),
    path("api/stocks", views.stocks_api, name="api-stocks"),
]

src/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect


def home(request: HttpRequest) -> HttpResponse:
    return HttpResponseRedirect(reverse("posts:page-posts"))


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("accounts.urls", "accounts"), namespace="accounts")),
    path("", include(("posts.urls", "posts"), namespace="posts")),
    path("", include(("lights.urls", "lights"), namespace="lights")),
    path("", include(("finance.urls", "finance"), namespace="finance")),
    path("", home, name="home"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/finance/views.py
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.apps import apps
from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseNotAllowed,
    HttpResponseServerError,
)
from .apps import FinanceConfig
from .services import StockPriceService


def stock_price_service() -> StockPriceService:
    config = apps.get_app_config("finance")
    assert isinstance(config, FinanceConfig)
    return config.stock_price_service


@login_required
def stocks_page(request: HttpRequest) -> HttpResponse:
    if request.method != "GET":
        return HttpResponseNotAllowed(["GET"])
    return render(request, "finance/stocks_page.html", {"title": "Finance"})


@login_required
def stocks_api(request: HttpRequest) -> HttpResponse:
    if request.method != "GET":
        return HttpResponseNotAllowed(["GET"])

    symbol = request.GET.get("symbol")
    if symbol is None or symbol == "":
        return HttpResponseBadRequest("Must provide stock symbol")
    symbol = symbol.upper()

    tz = ZoneInfo("America/New_York")
    today = datetime.now(tz)
    last_30_days = today - timedelta(days=30)
    try:
        image_data = stock_price_service().create_price_plot(
            symbol,
            last_30_days,
            today,
        )
    except:
        return HttpResponseServerError("Failed to load stock prices")

    return render(request, "finance/stock_price_plot.html", {"image_data": image_data})

src/finance/templates/finance/stock_price_plot.html
<img src="data:image/png;base64, {{ image_data }}" alt="Stock price plot" width="100%">

src/finance/templates/finance/stocks_page.html
{% extends 'nav_page.html' %}

{% load static %}

{% block title %}
  Stocks
{% endblock %}

{% block style %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/finance/stocks_page.css' %}">
{% endblock %}

{% block body %}
  <main class="stocks-container">
    <div>
      <form
        hx-get="{% url 'finance:api-stocks' %}"
        hx-params="symbol"
        hx-target="#stocks-price-plot"
        hx-on::before-request="
          updateById('stocks-error', { text: '', style: { display: 'none' } });
          setEnabledById('stocks-button', false);
        "
        hx-on::after-request="setEnabledById('stocks-button', true);"
        hx-on::response-error="
          updateById('stocks-error', {
            text: event.detail.xhr.responseText,
            style: { display: 'block' },
          });
        "
      >
        <div class="stocks-symbol-entry-container">
          <div class="stocks-symbol-input-container">
            <input
              class="text-body stocks-symbol-input"
              name="symbol"
              type="text"
              placeholder="Ticker"
            >
          </div>
          <div>
            <button
              id="stocks-button"
              class="button-primary submit-button"
              type="submit"
            >
              Submit
            </button>
          </div>
        </div>
        <div class="stocks-loading-indicator-container">
          <div class="block-indicator text-subtitle">
            Loading...
          </div>
        </div>
      </form>
      <div class="stocks-price-plot-container">
        <div
          id="stocks-error"
          class="text-body stocks-error"
          style="display: none;"
        ></div>
        <div id="stocks-price-plot"></div>
      </div>
    </div>
  </main>
{% endblock %}