src/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect


def home(request: HttpRequest) -> HttpResponse:
    return HttpResponseRedirect(reverse("posts:page-posts"))


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("accounts.urls", "accounts"), namespace="accounts")),
    path("", include(("posts.urls", "posts"), namespace="posts")),
    path("", include(("lights.urls", "lights"), namespace="lights")),
    path("", include(("finance.urls", "finance"), namespace="finance")),
    path("", home, name="home"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("posts", views.posts_page, name="page-posts"),
    path("api/posts", views.posts_api, name="api-posts"),
    path("api/posts/<int:post_id>", views.posts_api, name="api-posts-one"),
    path(
        "api/posts/<int:post_id>/edit/start",
        views.start_edit_post,
        name="api-posts-edit-start",
    ),
    path(
        "api/posts/<int:post_id>/edit/cancel",
        views.cancel_edit_post,
        name="api-posts-edit-cancel",
    ),
]

src/posts/models.py
from datetime import datetime
from zoneinfo import ZoneInfo
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    id = models.BigAutoField(primary_key=True)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    content = models.TextField(max_length=1024)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(null=True, default=None)

    def __str__(self):
        # pylint: disable=no-member
        date_string = self.created_at.strftime("%Y-%m-%dT%H:%M:%S")
        return f"{self.id}-{self.author_name()}-{date_string}"

    def author_name(self):
        return self.author.username if self.author is not None else "user"

    def created_at_string(self):
        # pylint: disable=no-member
        tz = ZoneInfo("America/New_York")
        zoned_datetime = self.created_at.astimezone(tz)
        zoned_date = zoned_datetime.date()
        today = datetime.now(tz).date()
        if zoned_date == today:
            return f"at {zoned_datetime.strftime('%-I:%M %p')}"
        if zoned_date.year == today.year:
            return f"on {zoned_datetime.strftime('%-m/%-d')}"
        return f"on {zoned_date.strftime('%-m/%-d/%y')}"

    def is_edited(self):
        return self.updated_at is not None

src/posts/views.py
from datetime import datetime
from zoneinfo import ZoneInfo
from typing import Optional
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseNotFound,
    HttpResponseNotAllowed,
    QueryDict,
)
from .models import Post


@login_required
def posts_page(request: HttpRequest) -> HttpResponse:
    if request.method != "GET":
        return HttpResponseNotAllowed(["GET"])
    return render(request, "posts/posts_page.html", {"title": "Posts"})


@login_required
def start_edit_post(request: HttpRequest, post_id: Optional[int]) -> HttpResponse:
    if request.method != "GET":
        return HttpResponseNotAllowed(["GET"])

    try:
        post = Post.objects.get(id=post_id)
    except:
        return HttpResponseNotFound(f'Post with ID "{post_id}" not found')
    return render(request, "posts/edit_post_form.html", {"post": post})


@login_required
def cancel_edit_post(request: HttpRequest, post_id: Optional[int]) -> HttpResponse:
    if request.method != "GET":
        return HttpResponseNotAllowed(["GET"])

    try:
        post = Post.objects.get(id=post_id)
    except:
        return HttpResponseNotFound(f'Post with ID "{post_id}" not found')
    return render(request, "posts/post_content.html", {"post": post})


@login_required
def posts_api(request: HttpRequest, post_id: Optional[int] = None) -> HttpResponse:
    if request.method == "GET":
        return get_posts(request, post_id)
    if request.method == "POST":
        return create_post(request)
    if request.method == "PATCH":
        return update_post(request, post_id)
    if request.method == "DELETE":
        return delete_post(request, post_id)
    return HttpResponseNotAllowed(["GET", "POST", "PATCH", "DELETE"])


def get_posts(request: HttpRequest, post_id: Optional[int] = None) -> HttpResponse:
    if post_id is not None:
        try:
            post = Post.objects.get(id=post_id)
        except:
            return HttpResponseNotFound(f'Post with id "{post_id}" not found')
        return render(request, "posts/post_content.html", {"post": post})

    posts = Post.objects.all().order_by("-created_at")
    return render(request, "posts/posts_list.html", {"posts": posts})


def create_post(request: HttpRequest) -> HttpResponse:
    content = request.POST.get("content")
    if content is None:
        return HttpResponseBadRequest("Post requires content to create")

    user = request.user
    post = Post.objects.create(author=user, content=content)
    return render(request, "posts/post_content.html", {"post": post})


def update_post(request: HttpRequest, post_id: Optional[int] = None) -> HttpResponse:
    if post_id is None:
        return HttpResponseBadRequest("Post ID is required to update")

    body = QueryDict(request.body)
    content = body.get("content")
    try:
        post = Post.objects.get(id=post_id)
    except:
        return HttpResponseNotFound(f'User with username "{post_id}" not found')
    if content is not None and content != post.content:
        post.content = content
        post.updated_at = datetime.now(ZoneInfo("UTC"))
    post.save()
    return render(request, "posts/post_content.html", {"post": post})


def delete_post(request: HttpRequest, post_id: Optional[int] = None) -> HttpResponse:
    if post_id is None:
        return HttpResponseBadRequest("Post ID is required to delete")

    try:
        post = Post.objects.get(id=post_id)
    except:
        return HttpResponseNotFound(f'User with username "{post_id}" not found')
    post.delete()
    return HttpResponse()

src/posts/templates/posts/create_post_form.html
<div id="create-post-form" class="post-outer" style="display: none">
  <div class="post-inner">
    <h1 class="text-body create-post-header">New Post</h1>
    <form
      hx-post="{% url 'posts:api-posts' %}"
      hx-target="#create-post-form"
      hx-swap="afterend"
      hx-on::after-request="setCssById('create-post-form', { display: 'none' })"
    >
      {% csrf_token %}
      <div class="create-post-textarea-container">
        <textarea
          id="content-textarea"
          class="text-body create-post-textarea"
          name="content"
          type="text"
          placeholder="Write post here..."
          rows="10"
        ></textarea>
      </div>
      <div class="post-button-row">
        <div class="post-left-button-container">
          <button
            class="button-primary text-body post-button"
            type="submit"
          >
            Create
          </button>
        </div>
        <div class="post-right-button-container">
          <button
            class="button-secondary text-body post-button"
            type="button"
            hx-on:click="setCssById('create-post-form', { display: 'none' })"
          >
            Cancel
          </button>
        </div>
      </div>
    </form>
  </div>
</div>

src/posts/templates/posts/edit_post_form.html
<div id="edit-post-form-{{ post.id }}" class="post-outer">
  <div class="post-inner">
    <div class="post-header">
      <h1 class="text-body post-title">
        <b>{{ post.author_name }}</b> {{ post.created_at_string }}{% if post.is_edited %} <i class="post-edited">(edited)</i>{% endif %}
      </h1>
    </div>
    <div>
      <div class="create-post-textarea-container">
        <textarea
          id="content-textarea-{{ post.id }}"
          class="text-body create-post-textarea"
          name="content"
          type="text"
          placeholder="Write post..."
          rows="10"
        >{{ post.content }}</textarea>
      </div>
      <div class="post-button-row">
        <div class="post-left-button-container">
          <button
            class="button-primary text-body post-button"
            type="button"
            hx-patch="{% url 'posts:api-posts-one' post_id=post.id %}"
            hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
            hx-include="#content-textarea-{{ post.id }}"
            hx-target="#edit-post-form-{{ post.id }}"
            hx-swap="outerHTML"
          >
            Update
          </button>
        </div>
        <div class="post-right-button-container">
          <button
            class="button-secondary text-body post-button"
            type="button"
            hx-get="{% url 'posts:api-posts-edit-cancel' post_id=post.id %}"
            hx-target="#edit-post-form-{{ post.id }}"
            hx-swap="outerHTML"
          >
            Cancel
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

src/posts/templates/posts/post_content.html
<div id="post-content-{{ post.id }}" class="post-outer">
  <div class="post-inner">
    <div class="post-header">
      <h1 class="text-body post-title">
        <b>{{ post.author_name }}</b> {{ post.created_at_string }}{% if post.is_edited %} <i class="post-edited">(edited)</i>{% endif %}
      </h1>
      <div class="post-header-button-row">
        <div class="post-header-button">
          <button
            type="button"
            hx-get="{% url 'posts:api-posts-edit-start' post_id=post.id %}"
            hx-target="#post-content-{{ post.id }}"
            hx-swap="outerHTML"
          >
            {% include 'icons/edit.svg' %}
          </button>
        </div>
        <div>
          <button
            type="button"
            hx-delete="{% url 'posts:api-posts-one' post_id=post.id %}"
            hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
            hx-target="#post-content-{{ post.id }}"
            hx-swap="delete"
          >
            {% include 'icons/delete.svg' %}
          </button>
        </div>
      </div>
    </div>
    <p class="text-body">
      {{ post.content }}
    </p>
  </div>
</div>

src/posts/templates/posts/posts_list.html
{% include 'posts/create_post_form.html' %}
{% for post in posts %}
  {% include 'posts/post_content.html' with post=post %}
{% endfor %}

src/posts/templates/posts/posts_page.html
{% extends 'nav_page.html' %}

{% load static %}

{% block title %}
  Posts
{% endblock %}

{% block style %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/posts/posts_page.css' %}">
{% endblock %}

{% block body %}
  <main class="post-list-container">
    <div
      class="post-list-layout"
      hx-get="{% url 'posts:api-posts' %}"
      hx-trigger="load"
    ></div>
  </div>
  <div class="post-create-button-container">
    <button
      class="button-fab"
      type="button"
      hx-on:click="setCssById('create-post-form', { display: 'block' })"
    >
      {% include 'icons/plus.svg' %}
    </button>
  </main>
{% endblock %}