src/lights/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("lights", views.lights_page, name="page-lights"),
    path("api/lights", views.lights_api, name="api-lights"),
    path(
        "api/lights/pattern/add",
        views.add_light_pattern_step,
        name="api-lights-pattern-add",
    ),
    path(
        "api/lights/pattern/set",
        views.set_light_pattern,
        name="api-lights-pattern-set",
    ),
    path(
        "api/lights/anim/add",
        views.add_light_animation,
        name="api-lights-anim-add",
    ),
    path(
        "api/lights/anim/play",
        views.play_light_animation,
        name="api-lights-anim-play",
    ),
    path("api/lights/clear", views.clear_lights, name="api-lights-clear"),
]

src/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect


def home(request: HttpRequest) -> HttpResponse:
    return HttpResponseRedirect(reverse("posts:page-posts"))


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("accounts.urls", "accounts"), namespace="accounts")),
    path("", include(("posts.urls", "posts"), namespace="posts")),
    path("", include(("lights.urls", "lights"), namespace="lights")),
    path("", include(("finance.urls", "finance"), namespace="finance")),
    path("", home, name="home"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/lights/models.py
from typing import Optional
from django.db import models


class ColorPatternStep:
    color: tuple[int, int, int]
    step: int

    def __init__(self, color: tuple[int, int, int], step: int):
        self.color = color
        self.step = step


class ColorAnimation:
    colors: list[ColorPatternStep]
    duration: Optional[float]

    def __init__(self, colors: list[ColorPatternStep], duration: Optional[float]):
        self.colors = colors
        self.duration = duration


class SequenceColorAnimation(ColorAnimation):
    pass


class FadeColorAnimation(ColorAnimation):
    start: Optional[float]
    end: Optional[float]

    def __init__(
        self,
        colors: list[ColorPatternStep],
        duration: Optional[float],
        start: Optional[float],
        end: Optional[float],
    ):
        super().__init__(colors, duration)
        self.start = start
        self.end = end


class LinearSweepColorAnimation(ColorAnimation):
    start: Optional[int]
    end: Optional[int]

    def __init__(
        self,
        colors: list[ColorPatternStep],
        duration: Optional[float],
        start: Optional[int],
        end: Optional[int],
    ):
        super().__init__(colors, duration)
        self.start = start
        self.end = end


class BinarySweepColorAnimation(ColorAnimation):
    start: Optional[int]
    end: Optional[int]

    def __init__(
        self,
        colors: list[ColorPatternStep],
        duration: Optional[float],
        start: Optional[int],
        end: Optional[int],
    ):
        super().__init__(colors, duration)
        self.start = start
        self.end = end


class SnakeColorAnimation(ColorAnimation):
    start: Optional[int]
    end: Optional[int]
    length: Optional[int]

    def __init__(
        self,
        colors: list[ColorPatternStep],
        duration: Optional[float],
        start: Optional[int],
        end: Optional[int],
        length: Optional[int],
    ):
        super().__init__(colors, duration)
        self.start = start
        self.end = end
        self.length = length

src/lights/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.apps import apps
from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseNotAllowed,
)
from .apps import LightsConfig
from .services.light_strip import LightStripService
from .util import color_from_hue, pattern_from_colors


def light_strip_service() -> LightStripService:
    config = apps.get_app_config("lights")
    assert isinstance(config, LightsConfig)
    return config.light_strip_service


@login_required
def lights_page(request: HttpRequest) -> HttpResponse:
    if request.method != "GET":
        return HttpResponseNotAllowed(["GET"])
    return render(request, "lights/lights_page.html", {"title": "Lights"})


@login_required
def lights_api(request: HttpRequest) -> HttpResponse:
    if request.method != "GET":
        return HttpResponseNotAllowed(["GET"])
    lights = light_strip_service().get_leds()
    return render(request, "lights/lights_display.html", {"lights": lights})


@login_required
def add_light_pattern_step(request: HttpRequest) -> HttpResponse:
    if request.method != "GET":
        return HttpResponseNotAllowed(["GET"])
    index = int(request.GET.get("index", 0))
    return render(request, "lights/color_pattern_step_form.html", {"index": index + 1})


@login_required
def set_light_pattern(request: HttpRequest) -> HttpResponse:
    if request.method != "POST":
        return HttpResponseNotAllowed(["POST"])

    colors = request.POST.getlist("color[]")
    if colors is None or len(colors) == 0:
        return HttpResponseBadRequest("Missing info")
    if len(colors) == 1:
        hue = int(colors[0])
        r, g, b = color_from_hue(hue)
        light_strip_service().set_solid_color(r, g, b)
    else:
        pattern = pattern_from_colors(colors)
        light_strip_service().set_pattern(pattern)

    response = HttpResponse()
    response["HX-Trigger"] = "lights-update"
    return response


@login_required
def clear_lights(request: HttpRequest) -> HttpResponse:
    if request.method != "POST":
        return HttpResponseNotAllowed(["POST"])

    light_strip_service().clear_color()

    response = render(request, "lights/color_pattern_step_form.html", {"index": 0})
    response["HX-Trigger"] = "lights-update"
    return response


@login_required
def add_light_animation(request: HttpRequest) -> HttpResponse:
    # TODO: Implement
    return HttpResponse()


@login_required
def play_light_animation(request: HttpRequest) -> HttpResponse:
    # TODO: Implement
    return HttpResponse()

src/lights/templates/lights/color_pattern_step_form.html
<div id="lights-pattern-step-{{ index }}" class="lights-pattern-step">
  <div
    id="lights-color-{{ index }}"
    class="lights-color"
    style="background-color: black;"
  ></div>
  <div class="lights-color-input-container">
    <input
      class="lights-color-input"
      name="color[]"
      type="range"
      min="0"
      max="255"
      value="0"
      hx-on:input="setCssById('lights-color-{{ index }}', { 'background-color': colorFromHue(+event.target.value) })"
    >
  </div>
  {% if index > 0 %}
    <div class="lights-remove-button-container">
      <button
        class="lights-remove-button"
        hx-on:click="deleteById('lights-pattern-step-{{ index }}')"
      >
        X
      </button>
    </div>
  {% endif %}
</div>
<div id="lights-add-step" class="lights-add-step-button-container">
  <button
    class="button-fab"
    type="button"
    hx-get="{% url 'lights:api-lights-pattern-add'%}?index={{ index }}"
    hx-target="#lights-add-step"
    hx-swap="outerHTML"
  >
    {% include 'icons/plus.svg' %}
  </button>
</div>

src/lights/templates/lights/lights_display.html
<div id="lights-display" class="lights-display">
  {% for light in lights %}
    <div
      class="lights-light"
      style="background-color: rgb({{ light.0 }}, {{ light.1 }}, {{ light.2 }});"
    ></div>
  {% endfor %}
</div>

src/lights/templates/lights/lights_page.html
{% extends 'nav_page.html' %}

{% load static %}

{% block title %}
  Lights
{% endblock %}

{% block style %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/lights/lights_page.css' %}">
{% endblock %}

{% block body %}
  <main class="lights-container">
    <div
      hx-get="{% url 'lights:api-lights' %}"
      hx-trigger="load, lights-update from:body"
      hx-swap="innerHTML"
    ></div>
    <div class="lights-layout">
      <div class="lights-form-container">
        <form
          hx-post="{% url 'lights:api-lights-pattern-set' %}"
          hx-swap="none"
          hx-on::before-request="
            setEnabledById('lights-set-button', false);
            setEnabledById('lights-clear-button', false);
          "
          hx-on::after-request="
            setEnabledById('lights-set-button', true);
            setEnabledById('lights-clear-button', true);
          "
        >
          {% csrf_token %}
          <div class="lights-main-controls-container">
            <div class="lights-select-container">
              <select class="lights-select">
                <option selected>Color</option>
                <option>Animation</option>
              </select>
            </div>
            <div class="lights-submit-button-container">
              <button
                id="lights-set-button"
                class="button-primary submit-button lights-submit-button"
                type="submit"
              >
                Set
              </button>
              <button
                id="lights-clear-button"
                class="button-primary submit-button lights-submit-button"
                type="button"
                hx-post="{% url 'lights:api-lights-clear' %}"
                hx-target="#lights-pattern"
                hx-swap="innerHTML"
                hx-on::before-request="
                  setEnabledById('lights-set-button', false);
                  setEnabledById('lights-clear-button', false);
                "
                hx-on::after-request="
                  setEnabledById('lights-set-button', true);
                  setEnabledById('lights-clear-button', true);
                "
              >
                Clear
              </button>
            </div>
          </div>
          <div id="lights-pattern">
            {% include 'lights/color_pattern_step_form.html' with index=0 %}
          </div>
        </form>
      </div>
    </div>
  </main>
{% endblock %}